baseURL = "https://example.org/"
canonifyurls = true
defaultContentLanguage = "en-us"
languageCode = "en-us"
paginate = 6
theme = "hugo-tranquilpeak-theme"
title = "Hugo tranquilpeak theme"
[author]
bio = ""
job = "Femme au foyer"
location = "Québec"
name = "Marie Rochat"
picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
[[menu.main]]
identifier = "about"
name = "Qui suis-je?"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
url = "/#about"
weight = 4
[[menu.main]]
identifier = "archives"
name = "Archives"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
url = "/archives"
weight = 3
[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/tags"
weight = 2
[[menu.main]]
identifier = "home"
name = "Page principale"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"
weight = 1
[[menu.misc]]
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
url = "/index.xml"
weight = 1
[params]
autothumbnailimage = true
clearreading = false
coverimage = "cover.jpg"
description = ""
favicon = "/favicon.png"
hierarchicalcategories = false
imagegallery = false
sidebarbehavior = 1
syntaxhighlighter = "highlight.js"
thumbnailimage = true
thumbnailimageposition = "bottom"
[params.header.rightlink]
class = ""
icon = ""
url = "/#about"
[[params.sharingoptions]]
icon = "fa-facebook-official"
name = "Facebook"
url = "https://www.facebook.com/sharer/sharer.php?u=%s"
[[params.sharingoptions]]
icon = "fa-twitter"
name = "Twitter"
url = "https://twitter.com/intent/tweet?text=%s"
[[params.sharingoptions]]
icon = "fa-google-plus"
name = "Google+"
url = "https://plus.google.com/share?url=%s"
[permalinks]
post = "/:year/:month/:slug/"
[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
